export default [
    {
        files: ['src/**/*.js', 'scripts/*.js'],
        languageOptions: {
            ecmaVersion: 2024,
            sourceType: 'module',
            globals: {
                console: 'readonly',
                process: 'readonly',
                Bun: 'readonly',
                Buffer: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                clearTimeout: 'readonly',
                fetch: 'readonly',
                crypto: 'readonly',
                TextEncoder: 'readonly',
                TextDecoder: 'readonly',
                Response: 'readonly',
                Request: 'readonly',
                Headers: 'readonly',
                FormData: 'readonly',
                AbortController: 'readonly',
                AbortSignal: 'readonly',
                performance: 'readonly',
                __dirname: 'readonly',
            }
        },
        rules: {
            'no-undef': 'off',
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-constant-condition': 'warn',
            'no-debugger': 'error',
            'no-dupe-keys': 'warn',
            'no-duplicate-case': 'error',
            'no-unreachable': 'warn',
            'eqeqeq': ['warn', 'smart'],
        }
    },
    {
        files: ['src/shared/utils/ar-preview.js', 'src/frontend/**/*.js'],
        languageOptions: {
            globals: {
                document: 'readonly',
                window: 'readonly',
                navigator: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                location: 'readonly',
                history: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                Image: 'readonly',
                HTMLElement: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLFormElement: 'readonly',
                FileReader: 'readonly',
                Blob: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                ResizeObserver: 'readonly',
                DOMParser: 'readonly',
                XMLSerializer: 'readonly',
                getComputedStyle: 'readonly',
                matchMedia: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                btoa: 'readonly',
                atob: 'readonly',
            }
        },
        rules: {
            'no-undef': 'off',
        }
    },
    {
        ignores: [
            'node_modules/**',
            'src/frontend/core-bundle.js',
            'src/frontend/app.js',
            'playwright-report/**',
            'data/**',
            'logs/**',
            'chrome-extension/**',
            'mobile/**',
            'e2e/**',
            '.claude/**',
        ]
    }
];
