sonar.projectKey=Vaultifacts_VaultLister-3.0
sonar.organization=vaultlister

sonar.sources=src/backend,src/frontend,src/shared
sonar.tests=src/tests
sonar.exclusions=**/node_modules/**,dist/**,coverage/**,screenshots/**,data/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
