-- Migration 007: Seed roadmap_features and help_faq tables
-- Idempotent: ON CONFLICT (id) DO NOTHING

-- Roadmap features

INSERT INTO roadmap_features (id, title, description, status, category, eta, votes)
VALUES
    (gen_random_uuid()::TEXT, 'eBay Bot Automation',
     'Playwright-powered cross-listing and inventory sync for eBay listings',
     'in_progress', 'automations', NULL, 47),
    (gen_random_uuid()::TEXT, 'EasyPost Shipping Labels',
     'Print shipping labels via EasyPost. Supports Canada Post, FedEx, UPS, USPS, DHL.',
     'in_progress', 'shipping', NULL, 38),
    (gen_random_uuid()::TEXT, 'Stripe Billing & Subscriptions',
     'Pro and Business plans with Stripe. Manage subscriptions and billing history.',
     'in_progress', 'billing', NULL, 29),
    (gen_random_uuid()::TEXT, 'Mobile App (iOS & Android)',
     'Native mobile app for managing listings, scanning barcodes, and shooting photos on the go.',
     'planned', 'mobile', 'Q3 2026', 112),
    (gen_random_uuid()::TEXT, 'Bulk Listing Import from CSV',
     'Import hundreds of listings at once from a spreadsheet. Auto-map columns to inventory fields.',
     'planned', 'listings', 'Q2 2026', 89),
    (gen_random_uuid()::TEXT, 'AI Price Suggestions',
     'Claude AI analyzes sold comps across platforms and suggests optimal listing prices for each item.',
     'planned', 'ai', 'Q2 2026', 78),
    (gen_random_uuid()::TEXT, 'Chrome Extension v2',
     'Enhanced Chrome extension with one-click cross-listing from any marketplace product page.',
     'planned', 'chrome', 'Q2 2026', 65),
    (gen_random_uuid()::TEXT, 'Whatnot Live Show Integration',
     'Schedule and manage Whatnot live shows, bulk list items for auction, auto-end shows.',
     'planned', 'automations', 'Q3 2026', 54),
    (gen_random_uuid()::TEXT, 'Multi-User Teams',
     'Invite team members with role-based access. Perfect for reselling businesses with employees.',
     'planned', 'account', 'Q4 2026', 43),
    (gen_random_uuid()::TEXT, 'Buyer CRM & Repeat Customer Tracking',
     'Track buyer history, flag repeat customers, send personalized follow-ups.',
     'planned', 'analytics', 'Q3 2026', 31),
    (gen_random_uuid()::TEXT, 'Automated Return Management',
     'Auto-approve returns, generate return labels, restock inventory when items come back.',
     'planned', 'orders', 'Q3 2026', 28),
    (gen_random_uuid()::TEXT, 'Poshmark Closet Sharing Bot',
     'Automated closet sharing with human-like delays and CAPTCHA detection.',
     'completed', 'automations', NULL, 156)
ON CONFLICT (id) DO NOTHING;

-- Help FAQ entries

INSERT INTO help_faq (id, question, answer, category, position)
VALUES
    (gen_random_uuid()::TEXT,
     'How do I add my first item to inventory?',
     'Go to Inventory → click ''Add Item''. Fill in the title, condition, cost, and photos. Once saved, you can cross-list to any connected marketplace with one click.',
     'getting-started', 1),
    (gen_random_uuid()::TEXT,
     'Which marketplaces does VaultLister support?',
     'VaultLister supports Poshmark, eBay, Depop, Grailed, Mercari, Facebook Marketplace, Shopify, and Whatnot. Connect each platform in Settings → My Shops.',
     'getting-started', 2),
    (gen_random_uuid()::TEXT,
     'How do I connect my Poshmark account?',
     'Go to Settings → My Shops → click Connect next to Poshmark. Enter your Poshmark username and password. VaultLister uses secure browser automation (no API key required).',
     'getting-started', 3),
    (gen_random_uuid()::TEXT,
     'What is the Listing Health Score?',
     'The Listing Health Score measures the freshness of your active listings. Listings older than 30 days are considered stale. A score of 80%+ is Excellent, 50–79% is Good, and below 50% Needs Work.',
     'listings', 1),
    (gen_random_uuid()::TEXT,
     'How does cross-listing work?',
     'Open any inventory item, click ''Cross-List'', select the platforms, customize the title and price per platform if needed, then click Publish. VaultLister uses automation to post directly to each marketplace.',
     'listings', 2),
    (gen_random_uuid()::TEXT,
     'Can I set different prices per platform?',
     'Yes! When cross-listing, each platform card shows a price field you can customize. Poshmark usually needs higher prices (they take 20%), while Depop takes 10%.',
     'listings', 3),
    (gen_random_uuid()::TEXT,
     'How do I mark an order as shipped?',
     'Go to Orders → find the order → click ''Ship''. Enter the tracking number and carrier, then save. The buyer is automatically notified on supported platforms.',
     'orders', 1),
    (gen_random_uuid()::TEXT,
     'How does the shipping calculator work?',
     'The shipping calculator estimates shipping costs based on item weight and destination. Go to Orders → click ''Shipping Calculator''. Enter weight, dimensions, and postal codes to compare rates.',
     'orders', 2),
    (gen_random_uuid()::TEXT,
     'What does the free plan include?',
     'The free plan includes up to 50 inventory items, basic cross-listing, and sales tracking. Upgrade to Pro for unlimited items, AI features, automation bots, and priority support.',
     'pricing', 1),
    (gen_random_uuid()::TEXT,
     'Can I cancel my subscription anytime?',
     'Yes! You can cancel anytime from Settings → Plans & Billing. Your access continues until the end of the billing period. No cancellation fees.',
     'pricing', 2),
    (gen_random_uuid()::TEXT,
     'Is the Poshmark sharing bot safe to use?',
     'Yes — VaultLister''s sharing bot uses human-like delays and randomization to avoid detection. It respects Poshmark''s rate limits (max 30 shares/hour). CAPTCHA detection automatically stops the bot.',
     'automations', 1),
    (gen_random_uuid()::TEXT,
     'How do I set up automatic offers to likers?',
     'Go to Automations → Offer Rules. Create a rule: select Poshmark, set the discount percentage (10–30% recommended), minimum days listed, and minimum number of likers. Enable the rule to start sending offers automatically.',
     'automations', 2)
ON CONFLICT (id) DO NOTHING;
