name: Add to Project Board

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

permissions: {}

jobs:
  add-to-development-board:
    name: Add to Development Board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Vaultifacts/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          labeled: launch-checklist
          label-operator: NOT

  add-to-launch-checklist:
    name: Add to Launch Checklist Board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Vaultifacts/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          labeled: launch-checklist
