name: Semgrep

on:
  workflow_dispatch: {}
  schedule:
    - cron: "51 8 * * *"

concurrency:
  group: semgrep-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Semgrep
        run: semgrep ci --exclude .github/workflows/sonarcloud.yml
