name: Semgrep

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "51 8 * * *"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Semgrep
        run: semgrep ci --sarif-output results.sarif --exclude .github/workflows/sonarcloud.yml
        continue-on-error: true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@7fc1baf373eb073c686865bd453d412d506a05a2 # v3.35.1
        if: always()
        with:
          sarif_file: results.sarif
          category: semgrep
